### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by PPG007** [PPG007/pchat#8]

**Comment by PPG007** [comment]
TODO 相关：

- [x] todo、todoRecord 表定义。
- [x] 创建 todo。
- [x] 删除 todo。
- [x] 标记为已完成。
- [x] 标记为未完成。
- [x] 定时提醒。
- [x] 搜索 todoRecord。
- [x] 编辑 todo。
- [x] 根据 todo 生成 todoRecord。
- [x] 节假日规则。
- [x] 获取 todo 详情。

**Comment by PPG007** [comment]
chat backend 相关：

- [x] websocket 连接管理。
- [ ] 多连接内传递数据。
- [x] 定义 ws 事件结构。
- [x] 心跳检测。
- [ ] 创建、删除、搜索 chat。
- [ ] 搜索消息。
- [ ] 讨论串。
- [ ] 收藏消息、chat。
- [ ] 待办机器人。
- [ ] chatgpt 机器人。
- [x] 接入 minio，支持 sign url。
- [ ] 支持 chat 级别的提醒设置。
- [ ] 支持讨论串提醒设置。
- [ ] 支持在线状态编辑。
- [ ] 。。。

**Comment by PPG007** [comment]
chat frontend 相关：

- [ ] 实现 chat 页面。
- [ ] 群组公告。
- [ ] websocket 心跳检测、断线重连。
- [ ] 支持已读未读查看。
- [ ] 支持 emoji。
- [ ] 支持粘贴图片。
- [ ] 支持点击图片查看预览图。
- [ ] 支持 Markdown 解析。
- [ ] 支持链接解析。
- [ ] 支持上传文件。
- [ ] 支持讨论串。
- [ ] 支持链接跳转至指定消息。
- [ ] 支持 `@` 提及。
- [ ] 支持搜索 chat。
- [ ] 支持 chat 内搜索信息。
- [ ] 支持收藏 chat。
- [ ] 实现 robot。
- [ ] 支持 emoji 回应。
- [ ] 支持标记为未读。
- [ ] 允许对每一个 chat 设定提醒设置。
- [ ] 允许忽略讨论串的提醒。
- [ ] 允许私有 chat。
- [ ] 未读消息提醒。
- [ ] 桌面弹窗提醒。
- [ ] 个人信息页面。
- [ ] 双因素认证页面。
- [ ] 权限管理页面。
- [ ] 支持移除消息。
- [ ] 支持编辑消息。
- [ ] 支持 copy 消息链接。
- [ ] 支持引用消息。
- [ ] 支持收藏消息。
- [ ] 待办页面嵌入机器人 chat 中。
- [ ] 创建、编辑、删除、查询待办。
- [ ] 上传文件。
- [ ] 设置提醒时间。
- [ ] 设置重复提醒规则。
- [ ] 支持在线状态。
- [ ] 。。。

**Comment by PPG007** [comment]
admin 控制：

- [ ] 邮箱服务器设置。
- [ ] openAI 设置。
- [ ] JWT 设置。
- [ ] OSS 设置。
- [ ] chat 设置。

**Comment by PPG007** [comment]
- [x] 权限控制。
